### ISSUE TITLE
Redis causes server to crash

### ISSUE THREAD

**Issue by Saif807380** [CommunityOfCoders/COCWebsite#104]
Traceback

```bash
events.js:292
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: connect ECONNREFUSED 127.0.0.1:6379
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[0] Emitted 'error' event on RedisClient instance at:
[0]     at RedisClient.on_error (/Users/saifkazi/Desktop/COCWebsite/server/node_modules/redis/index.js:341:14)
[0]     at Socket.<anonymous> (/Users/saifkazi/Desktop/COCWebsite/server/node_modules/redis/index.js:222:14)
[0]     at Socket.emit (events.js:315:20)
[0]     at emitErrorNT (internal/streams/destroy.js:106:8)
[0]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[0]     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
[0]   errno: -61,
[0]   code: 'ECONNREFUSED',
[0]   syscall: 'connect',
[0]   address: '127.0.0.1',
[0]   port: 6379
[0] }
[0] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Parth576** [comment]
It does not look like you have the redis server running on your local machine since port ```6379``` is the default port for redis. Install [redis](https://redis.io/download) and check if you can reproduce the issue?

**Comment by Saif807380** [comment]
We actually don't want to connect to redis. Earlier we had redis for caching however deploying it was an issue hence we decided to remove redis altogether. But there was a small part that was remaining to be removed which was causing this issue.
